#1. Importing the modules

In [ ]:
 import numpy as np
 import pandas as pd
 import matplotlib.pyplot as plt
 from sklearn import neighbors, metrics
 from sklearn.model_selection import train_test_split
 from sklearn.preprocessing import LabelEncoder

#2. Load the car evaluation dataset.


In [ ]:
url = 'https://raw.githubusercontent.com/palakgupta2712/Machine_learning/master/car.data'
data = pd.read_csv(url)
print(data.head())

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc


#3. Features and lables

In [ ]:
x = data.reindex(columns=['buying','maint','safety']).values
y = data.reindex(columns=['class']).values

print(x,y)

[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']] [['unacc']
 ['unacc']
 ['unacc']
 ...
 ['unacc']
 ['good']
 ['vgood']]


#4. Translating the data into numbers.


In [ ]:
#Translating the data for x 
LE = LabelEncoder()
for i in range(len(x[0])):
  x[:, i] = LE.fit_transform(x[:, i])
print("------x------\n",x)


#Translating the data for y
LE = LabelEncoder()
for i in range(len(y[0])):
  y[:, i] = LE.fit_transform(y[:, i])
print("------y------\n",y)

------x------
 [[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]
------y------
 [[2]
 [2]
 [2]
 ...
 [2]
 [1]
 [3]]


#5. Modeling KNN Classifier

In [ ]:
knn = neighbors.KNeighborsClassifier(n_neighbors=25, weights='uniform')
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)
y=y.astype('int') 
x=x.astype('int') 
knn.fit(x_train, y_train)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=25, p=2,
                     weights='uniform')

#6. Predictions and Accuracy

In [ ]:
prediction = knn.predict(x_test)
accuracy = metrics.accuracy_score(y_test, prediction)
print("predictions:: ", prediction)
print("accuracy:: ", accuracy)

predictions::  [2 2 3 3 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 0 0 3 0 2 0 2 2 2 0 2 2 2 0 2 2 0 2
 2 2 0 2 2 2 0 2 0 0 2 0 2 2 3 0 0 2 2 0 2 2 0 2 1 2 2 3 2 2 2 2 3 0 0 0 2
 2 2 2 2 2 2 2 2 0 2 2 0 1 1 2 2 2 2 2 2 2 3 2 2 2 2 2 2 2 0 2 0 2 2 0 1 2
 2 2 2 2 2 0 2 2 2 2 1 2 2 2 2 2 2 2 2 2 1 3 2 0 2 2 0 2 2 3 0 2 2 2 2 2 3
 2 2 1 2 2 1 2 2 2 2 2 2 2 2 1 2 1 2 2 0 2 0 0 2 2 2 2 0 0 0 2 2 2 2 2 1 0
 1 0 2 2 0 0 1 2 2 2 2 2 2 2 2 0 2 2 0 2 0 2 2 2 2 0 2 2 2 2 2 2 1 0 2 2 2
 2 0 2 2 2 2 2 2 0 2 2 2 2 0 2 0 2 2 3 2 0 2 2 2 2 2 2 2 2 2 0 0 2 2 2 2 2
 0 2 2 0 2 2 1 2 2 2 2 0 2 3 2 2 2 2 0 2 3 2 2 2 2 2 2 2 0 0 2 1 2 2 0 0 0
 0 1 0 2 2 2 0 2 2 0 2 0 2 2 2 2 2 2 2 2 2 0 0 1 2 2 2 2 2 0 2 2 2 2 0 2 0
 2 2 2 2 2 2 0 2 2 2 2 2 2]
accuracy::  0.7543352601156069


#7. Testing our model


In [ ]:
a = 114
print("actual value", y[a])
print("predicted value", knn.predict(x)[a])

actual value [2]
predicted value 2
